services:
  - type: web
    name: fud-equiptrack
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: fud-equiptrack-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_CSRF_COOKIE_SECURE
        value: "True"
      - key: DJANGO_SESSION_COOKIE_SECURE
        value: "True"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: "True"

databases:
  - name: fud-equiptrack-db
    databaseName: fud_equiptrack
    user: fud_equiptrack
