# Generated by Django 6.0.6 on 2026-06-28 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('EQUIPMENT_ADDED', 'Equipment Added'), ('EQUIPMENT_UPDATED', 'Equipment Updated'), ('EQUIPMENT_DELETED', 'Equipment Deleted'), ('RENTAL_REQUEST_CREATED', 'Rental Request Created'), ('RENTAL_APPROVED', 'Rental Approved'), ('RENTAL_REJECTED', 'Rental Rejected'), ('EQUIPMENT_ISSUED', 'Equipment Issued'), ('EQUIPMENT_RETURNED', 'Equipment Returned'), ('USER_UPDATED', 'User Updated'), ('USER_SUSPENDED', 'User Suspended'), ('USER_ACTIVATED', 'User Activated'), ('REPORT_GENERATED', 'Report Generated')], db_index=True, max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of what happened.')),
                ('target_model', models.CharField(blank=True, help_text="e.g. 'Equipment', 'User', 'RentalRequest'", max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text='PK of the affected object.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='activitylog_action_5a535e_idx'), models.Index(fields=['-created_at'], name='activitylog_created_761286_idx'), models.Index(fields=['user', '-created_at'], name='activitylog_user_id_fb250e_idx')],
            },
        ),
    ]
