# Generated by Django 6.0.6 on 2026-06-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('LAPTOP', 'Laptop'), ('PROJECTOR', 'Projector'), ('PRINTER', 'Printer'), ('SCANNER', 'Scanner'), ('CAMERA', 'Camera'), ('NETWORKING', 'Networking Device')], db_index=True, default='LAPTOP', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('available_quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged')], default='EXCELLENT', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_images/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance')], db_index=True, default='AVAILABLE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='equipment_e_categor_11560f_idx'), models.Index(fields=['status'], name='equipment_e_status_fb8540_idx')],
            },
        ),
    ]
