# Generated by Django 5.2.14 on 2026-06-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('PROJECTOR', 'Projector'), ('PRINTER', 'Printer'), ('SCANNER', 'Scanner'), ('CAMERA', 'Camera'), ('NETWORKING', 'Networking Device')], default='LAPTOP', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=50),
        ),
    ]
