# Generated by Django 6.0.6 on 2026-06-23 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purpose', models.TextField()),
                ('request_date', models.DateField()),
                ('expected_return_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='equipment.equipment')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='rentals_ren_status_525c43_idx'), models.Index(fields=['requester'], name='rentals_ren_request_0e3a78_idx'), models.Index(fields=['equipment'], name='rentals_ren_equipme_e6d894_idx'), models.Index(fields=['request_date'], name='rentals_ren_request_458fe3_idx')],
            },
        ),
    ]
