# Generated by Django 6.0.6 on 2026-06-25 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('issued_date', models.DateField()),
                ('expected_return_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='equipment.equipment')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals_issued', to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals_received', to=settings.AUTH_USER_MODEL)),
                ('rental_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='rentals.rentalrequest')),
            ],
            options={
                'verbose_name': 'Rental',
                'verbose_name_plural': 'Rentals',
                'ordering': ['-issued_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='rentals_ren_status_fdfce4_idx'), models.Index(fields=['issued_to'], name='rentals_ren_issued__edc37c_idx'), models.Index(fields=['expected_return_date'], name='rentals_ren_expecte_fc5d00_idx')],
            },
        ),
    ]
