# Generated by Django 5.2.14 on 2026-06-26 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rental'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('condition_on_return', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='returns_record', to='rentals.rental')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
                'ordering': ['-return_date', '-created_at'],
                'indexes': [models.Index(fields=['rental'], name='rentals_ret_rental__082689_idx'), models.Index(fields=['returned_by'], name='rentals_ret_returne_02ed41_idx'), models.Index(fields=['return_date'], name='rentals_ret_return__1eeeab_idx'), models.Index(fields=['condition_on_return'], name='rentals_ret_conditi_e51a6f_idx')],
            },
        ),
    ]
