# Generated by Django 6.0.6 on 2026-06-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='approved_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
