# Generated by Django 5.2.14 on 2026-06-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rentalrequest_approved_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rental',
            name='rentals_ren_issued__edc37c_idx',
        ),
        migrations.RemoveIndex(
            model_name='rentalrequest',
            name='rentals_ren_request_0e3a78_idx',
        ),
        migrations.RemoveIndex(
            model_name='rentalrequest',
            name='rentals_ren_equipme_e6d894_idx',
        ),
        migrations.RemoveIndex(
            model_name='return',
            name='rentals_ret_rental__082689_idx',
        ),
        migrations.RemoveIndex(
            model_name='return',
            name='rentals_ret_returne_02ed41_idx',
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='return',
            name='condition_on_return',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], max_length=20),
        ),
    ]
