# Generated by Django 5.2.14 on 2026-06-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_phone_f54457_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_faculty_b9912f_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_departm_4298b0_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
